# Generated by Django 5.0.3 on 2024-03-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='progressreport',
            name='project',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='ProgressReport',
        ),
    ]
